package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Affiche generated by hbm2java
 */
public class Affiche implements java.io.Serializable {

	private Long id;
	private String code;
	private String title;
	private String content;
	private String publisher;
	private Date publishTime;
	private Date startTime;
	private Date endTime;

	public Affiche() {
	}

	public Affiche(String code, String title, String content, String publisher,
			Date publishTime, Date startTime, Date endTime) {
		this.code = code;
		this.title = title;
		this.content = content;
		this.publisher = publisher;
		this.publishTime = publishTime;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
