package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AuAuthority generated by hbm2java
 */
public class AuAuthority implements java.io.Serializable {

	private Long id;
	private Long roleId;
	private Long functionId;
	private Long userTypeId;
	private Date creationTime;
	private String createdBy;

	public AuAuthority() {
	}

	public AuAuthority(Long roleId, Long functionId, Long userTypeId,
			Date creationTime, String createdBy) {
		this.roleId = roleId;
		this.functionId = functionId;
		this.userTypeId = userTypeId;
		this.creationTime = creationTime;
		this.createdBy = createdBy;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public Long getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(Long functionId) {
		this.functionId = functionId;
	}

	public Long getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Long userTypeId) {
		this.userTypeId = userTypeId;
	}

	public Date getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
