package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AuRole generated by hbm2java
 */
public class AuRole implements java.io.Serializable {

	private Long id;
	private String roleCode;
	private String roleName;
	private Date createDate;
	private Integer isStart;
	private String createdBy;

	public AuRole() {
	}

	public AuRole(String roleCode, String roleName, Date createDate,
			Integer isStart, String createdBy) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.createDate = createDate;
		this.isStart = isStart;
		this.createdBy = createdBy;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getIsStart() {
		return this.isStart;
	}

	public void setIsStart(Integer isStart) {
		this.isStart = isStart;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
