package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AuUser generated by hbm2java
 */
public class AuUser implements java.io.Serializable {

	private Long id;
	private String loginCode;
	private String password;
	private String password2;
	private String userName;
	private String sex;
	private Date birthday;
	private String cardType;
	private String cardTypeName;
	private String idCard;
	private String country;
	private String mobile;
	private String email;
	private String userAddress;
	private String postCode;
	private Date createTime;
	private Long referId;
	private String referCode;
	private Long roleId;
	private String roleName;
	private String userType;
	private String userTypeName;
	private Integer isStart;
	private Date lastUpdateTime;
	private Date lastLoginTime;
	private String bankAccount;
	private String bankName;
	private String accountHolder;
	private String idCardPicPath;
	private String bankPicPath;

	public AuUser() {
	}

	public AuUser(String loginCode, String password, String password2,
			String userName, String sex, Date birthday, String cardType,
			String cardTypeName, String idCard, String country, String mobile,
			String email, String userAddress, String postCode, Date createTime,
			Long referId, String referCode, Long roleId, String roleName,
			String userType, String userTypeName, Integer isStart,
			Date lastUpdateTime, Date lastLoginTime, String bankAccount,
			String bankName, String accountHolder, String idCardPicPath,
			String bankPicPath) {
		this.loginCode = loginCode;
		this.password = password;
		this.password2 = password2;
		this.userName = userName;
		this.sex = sex;
		this.birthday = birthday;
		this.cardType = cardType;
		this.cardTypeName = cardTypeName;
		this.idCard = idCard;
		this.country = country;
		this.mobile = mobile;
		this.email = email;
		this.userAddress = userAddress;
		this.postCode = postCode;
		this.createTime = createTime;
		this.referId = referId;
		this.referCode = referCode;
		this.roleId = roleId;
		this.roleName = roleName;
		this.userType = userType;
		this.userTypeName = userTypeName;
		this.isStart = isStart;
		this.lastUpdateTime = lastUpdateTime;
		this.lastLoginTime = lastLoginTime;
		this.bankAccount = bankAccount;
		this.bankName = bankName;
		this.accountHolder = accountHolder;
		this.idCardPicPath = idCardPicPath;
		this.bankPicPath = bankPicPath;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLoginCode() {
		return this.loginCode;
	}

	public void setLoginCode(String loginCode) {
		this.loginCode = loginCode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword2() {
		return this.password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardTypeName() {
		return this.cardTypeName;
	}

	public void setCardTypeName(String cardTypeName) {
		this.cardTypeName = cardTypeName;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getReferId() {
		return this.referId;
	}

	public void setReferId(Long referId) {
		this.referId = referId;
	}

	public String getReferCode() {
		return this.referCode;
	}

	public void setReferCode(String referCode) {
		this.referCode = referCode;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public Integer getIsStart() {
		return this.isStart;
	}

	public void setIsStart(Integer isStart) {
		this.isStart = isStart;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getAccountHolder() {
		return this.accountHolder;
	}

	public void setAccountHolder(String accountHolder) {
		this.accountHolder = accountHolder;
	}

	public String getIdCardPicPath() {
		return this.idCardPicPath;
	}

	public void setIdCardPicPath(String idCardPicPath) {
		this.idCardPicPath = idCardPicPath;
	}

	public String getBankPicPath() {
		return this.bankPicPath;
	}

	public void setBankPicPath(String bankPicPath) {
		this.bankPicPath = bankPicPath;
	}

}
