package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

/**
 * BasicsParameter generated by hbm2java
 */
public class BasicsParameter implements java.io.Serializable {

	private String id;
	private String name;
	private String code;
	private String value;
	private String description;
	private String dr;

	public BasicsParameter() {
	}

	public BasicsParameter(String id) {
		this.id = id;
	}

	public BasicsParameter(String id, String name, String code, String value,
			String description, String dr) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.value = value;
		this.description = description;
		this.dr = dr;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDr() {
		return this.dr;
	}

	public void setDr(String dr) {
		this.dr = dr;
	}

}
