package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GoodsInfo generated by hbm2java
 */
public class GoodsInfo implements java.io.Serializable {

	private Long id;
	private String goodsSn;
	private String goodsName;
	private String goodsFormat;
	private Double marketPrice;
	private Double realPrice;
	private Integer state;
	private String note;
	private Integer num;
	private String unit;
	private Date createTime;
	private Date lastUpdateTime;
	private String createdBy;

	public GoodsInfo() {
	}

	public GoodsInfo(String goodsSn, String goodsName, String goodsFormat,
			Double marketPrice, Double realPrice, Integer state, String note,
			Integer num, String unit, Date createTime, Date lastUpdateTime,
			String createdBy) {
		this.goodsSn = goodsSn;
		this.goodsName = goodsName;
		this.goodsFormat = goodsFormat;
		this.marketPrice = marketPrice;
		this.realPrice = realPrice;
		this.state = state;
		this.note = note;
		this.num = num;
		this.unit = unit;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
		this.createdBy = createdBy;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGoodsSn() {
		return this.goodsSn;
	}

	public void setGoodsSn(String goodsSn) {
		this.goodsSn = goodsSn;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getGoodsFormat() {
		return this.goodsFormat;
	}

	public void setGoodsFormat(String goodsFormat) {
		this.goodsFormat = goodsFormat;
	}

	public Double getMarketPrice() {
		return this.marketPrice;
	}

	public void setMarketPrice(Double marketPrice) {
		this.marketPrice = marketPrice;
	}

	public Double getRealPrice() {
		return this.realPrice;
	}

	public void setRealPrice(Double realPrice) {
		this.realPrice = realPrice;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
