package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GoodsPack generated by hbm2java
 */
public class GoodsPack implements java.io.Serializable {

	private Long id;
	private String goodsPackName;
	private String goodsPackCode;
	private Integer typeId;
	private String typeName;
	private Double totalPrice;
	private Integer state;
	private String note;
	private Integer num;
	private String createdBy;
	private Date createTime;
	private Date lastUpdateTime;

	public GoodsPack() {
	}

	public GoodsPack(String goodsPackName, String goodsPackCode,
			Integer typeId, String typeName, Double totalPrice, Integer state,
			String note, Integer num, String createdBy, Date createTime,
			Date lastUpdateTime) {
		this.goodsPackName = goodsPackName;
		this.goodsPackCode = goodsPackCode;
		this.typeId = typeId;
		this.typeName = typeName;
		this.totalPrice = totalPrice;
		this.state = state;
		this.note = note;
		this.num = num;
		this.createdBy = createdBy;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGoodsPackName() {
		return this.goodsPackName;
	}

	public void setGoodsPackName(String goodsPackName) {
		this.goodsPackName = goodsPackName;
	}

	public String getGoodsPackCode() {
		return this.goodsPackCode;
	}

	public void setGoodsPackCode(String goodsPackCode) {
		this.goodsPackCode = goodsPackCode;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
