package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

/**
 * GoodsPackAffiliated generated by hbm2java
 */
public class GoodsPackAffiliated implements java.io.Serializable {

	private Long id;
	private Long goodsPackId;
	private Long goodsInfoId;
	private Integer goodsNum;

	public GoodsPackAffiliated() {
	}

	public GoodsPackAffiliated(Long goodsPackId, Long goodsInfoId,
			Integer goodsNum) {
		this.goodsPackId = goodsPackId;
		this.goodsInfoId = goodsInfoId;
		this.goodsNum = goodsNum;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getGoodsPackId() {
		return this.goodsPackId;
	}

	public void setGoodsPackId(Long goodsPackId) {
		this.goodsPackId = goodsPackId;
	}

	public Long getGoodsInfoId() {
		return this.goodsInfoId;
	}

	public void setGoodsInfoId(Long goodsInfoId) {
		this.goodsInfoId = goodsInfoId;
	}

	public Integer getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}

}
