package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InfoAnnexes generated by hbm2java
 */
public class InfoAnnexes implements java.io.Serializable {

	private String id;
	private String infoId;
	private String name;
	private String url;
	private String state;
	private String type;
	private Date uploadTime;
	private Integer size;

	public InfoAnnexes() {
	}

	public InfoAnnexes(String id) {
		this.id = id;
	}

	public InfoAnnexes(String id, String infoId, String name, String url,
			String state, String type, Date uploadTime, Integer size) {
		this.id = id;
		this.infoId = infoId;
		this.name = name;
		this.url = url;
		this.state = state;
		this.type = type;
		this.uploadTime = uploadTime;
		this.size = size;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

}
