package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LeaveMessage generated by hbm2java
 */
public class LeaveMessage implements java.io.Serializable {

	private Long id;
	private String createdBy;
	private String messageCode;
	private String messageTitle;
	private String messageContent;
	private Integer state;
	private Date createTime;

	public LeaveMessage() {
	}

	public LeaveMessage(String createdBy, String messageCode,
			String messageTitle, String messageContent, Integer state,
			Date createTime) {
		this.createdBy = createdBy;
		this.messageCode = messageCode;
		this.messageTitle = messageTitle;
		this.messageContent = messageContent;
		this.state = state;
		this.createTime = createTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(String messageCode) {
		this.messageCode = messageCode;
	}

	public String getMessageTitle() {
		return this.messageTitle;
	}

	public void setMessageTitle(String messageTitle) {
		this.messageTitle = messageTitle;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
