package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

/**
 * MultiLan generated by hbm2java
 */
public class MultiLan implements java.io.Serializable {

	private String elementId;
	private String pagePath;
	private String scn;
	private String tcn;
	private String en;
	private String jp;
	private String kr;
	private String fr;
	private String ra;

	public MultiLan() {
	}

	public MultiLan(String elementId) {
		this.elementId = elementId;
	}

	public MultiLan(String elementId, String pagePath, String scn, String tcn,
			String en, String jp, String kr, String fr, String ra) {
		this.elementId = elementId;
		this.pagePath = pagePath;
		this.scn = scn;
		this.tcn = tcn;
		this.en = en;
		this.jp = jp;
		this.kr = kr;
		this.fr = fr;
		this.ra = ra;
	}

	public String getElementId() {
		return this.elementId;
	}

	public void setElementId(String elementId) {
		this.elementId = elementId;
	}

	public String getPagePath() {
		return this.pagePath;
	}

	public void setPagePath(String pagePath) {
		this.pagePath = pagePath;
	}

	public String getScn() {
		return this.scn;
	}

	public void setScn(String scn) {
		this.scn = scn;
	}

	public String getTcn() {
		return this.tcn;
	}

	public void setTcn(String tcn) {
		this.tcn = tcn;
	}

	public String getEn() {
		return this.en;
	}

	public void setEn(String en) {
		this.en = en;
	}

	public String getJp() {
		return this.jp;
	}

	public void setJp(String jp) {
		this.jp = jp;
	}

	public String getKr() {
		return this.kr;
	}

	public void setKr(String kr) {
		this.kr = kr;
	}

	public String getFr() {
		return this.fr;
	}

	public void setFr(String fr) {
		this.fr = fr;
	}

	public String getRa() {
		return this.ra;
	}

	public void setRa(String ra) {
		this.ra = ra;
	}

}
