package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * OrderInfo generated by hbm2java
 */
public class OrderInfo implements java.io.Serializable {

	private String orderId;
	private String listId;
	private Date orderTime;
	private String orderSn;
	private String pickUserId;
	private BigDecimal repeatPv;
	private BigDecimal basePv;
	private BigDecimal serviceFee;
	private BigDecimal shipFre;
	private BigDecimal tax;
	private String country;
	private String tel;
	private String mobile;
	private String email;
	private String userAddress;
	private String postcode;
	private Integer stat;
	private String shipType;
	private String shipNum;
	private Date shipTime;
	private Date receiveTime;
	private String shipNote;
	private String buyUserId;

	public OrderInfo() {
	}

	public OrderInfo(String orderId, String buyUserId) {
		this.orderId = orderId;
		this.buyUserId = buyUserId;
	}

	public OrderInfo(String orderId, String listId, Date orderTime,
			String orderSn, String pickUserId, BigDecimal repeatPv,
			BigDecimal basePv, BigDecimal serviceFee, BigDecimal shipFre,
			BigDecimal tax, String country, String tel, String mobile,
			String email, String userAddress, String postcode, Integer stat,
			String shipType, String shipNum, Date shipTime, Date receiveTime,
			String shipNote, String buyUserId) {
		this.orderId = orderId;
		this.listId = listId;
		this.orderTime = orderTime;
		this.orderSn = orderSn;
		this.pickUserId = pickUserId;
		this.repeatPv = repeatPv;
		this.basePv = basePv;
		this.serviceFee = serviceFee;
		this.shipFre = shipFre;
		this.tax = tax;
		this.country = country;
		this.tel = tel;
		this.mobile = mobile;
		this.email = email;
		this.userAddress = userAddress;
		this.postcode = postcode;
		this.stat = stat;
		this.shipType = shipType;
		this.shipNum = shipNum;
		this.shipTime = shipTime;
		this.receiveTime = receiveTime;
		this.shipNote = shipNote;
		this.buyUserId = buyUserId;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getListId() {
		return this.listId;
	}

	public void setListId(String listId) {
		this.listId = listId;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getOrderSn() {
		return this.orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	public String getPickUserId() {
		return this.pickUserId;
	}

	public void setPickUserId(String pickUserId) {
		this.pickUserId = pickUserId;
	}

	public BigDecimal getRepeatPv() {
		return this.repeatPv;
	}

	public void setRepeatPv(BigDecimal repeatPv) {
		this.repeatPv = repeatPv;
	}

	public BigDecimal getBasePv() {
		return this.basePv;
	}

	public void setBasePv(BigDecimal basePv) {
		this.basePv = basePv;
	}

	public BigDecimal getServiceFee() {
		return this.serviceFee;
	}

	public void setServiceFee(BigDecimal serviceFee) {
		this.serviceFee = serviceFee;
	}

	public BigDecimal getShipFre() {
		return this.shipFre;
	}

	public void setShipFre(BigDecimal shipFre) {
		this.shipFre = shipFre;
	}

	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

	public String getShipType() {
		return this.shipType;
	}

	public void setShipType(String shipType) {
		this.shipType = shipType;
	}

	public String getShipNum() {
		return this.shipNum;
	}

	public void setShipNum(String shipNum) {
		this.shipNum = shipNum;
	}

	public Date getShipTime() {
		return this.shipTime;
	}

	public void setShipTime(Date shipTime) {
		this.shipTime = shipTime;
	}

	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public String getShipNote() {
		return this.shipNote;
	}

	public void setShipNote(String shipNote) {
		this.shipNote = shipNote;
	}

	public String getBuyUserId() {
		return this.buyUserId;
	}

	public void setBuyUserId(String buyUserId) {
		this.buyUserId = buyUserId;
	}

}
