package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OrderList generated by hbm2java
 */
public class OrderList implements java.io.Serializable {

	private String listId;
	private String goodsId;
	private String goodsSn;
	private String goodsName;
	private String goodsFormat;
	private Integer goodsNum;
	private BigDecimal eachPrice;
	private BigDecimal sumPrice;
	private BigDecimal discount;
	private BigDecimal realPrice;
	private String currency;
	private BigDecimal realPv;
	private BigDecimal pvRate;

	public OrderList() {
	}

	public OrderList(String listId) {
		this.listId = listId;
	}

	public OrderList(String listId, String goodsId, String goodsSn,
			String goodsName, String goodsFormat, Integer goodsNum,
			BigDecimal eachPrice, BigDecimal sumPrice, BigDecimal discount,
			BigDecimal realPrice, String currency, BigDecimal realPv,
			BigDecimal pvRate) {
		this.listId = listId;
		this.goodsId = goodsId;
		this.goodsSn = goodsSn;
		this.goodsName = goodsName;
		this.goodsFormat = goodsFormat;
		this.goodsNum = goodsNum;
		this.eachPrice = eachPrice;
		this.sumPrice = sumPrice;
		this.discount = discount;
		this.realPrice = realPrice;
		this.currency = currency;
		this.realPv = realPv;
		this.pvRate = pvRate;
	}

	public String getListId() {
		return this.listId;
	}

	public void setListId(String listId) {
		this.listId = listId;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getGoodsSn() {
		return this.goodsSn;
	}

	public void setGoodsSn(String goodsSn) {
		this.goodsSn = goodsSn;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getGoodsFormat() {
		return this.goodsFormat;
	}

	public void setGoodsFormat(String goodsFormat) {
		this.goodsFormat = goodsFormat;
	}

	public Integer getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}

	public BigDecimal getEachPrice() {
		return this.eachPrice;
	}

	public void setEachPrice(BigDecimal eachPrice) {
		this.eachPrice = eachPrice;
	}

	public BigDecimal getSumPrice() {
		return this.sumPrice;
	}

	public void setSumPrice(BigDecimal sumPrice) {
		this.sumPrice = sumPrice;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getRealPrice() {
		return this.realPrice;
	}

	public void setRealPrice(BigDecimal realPrice) {
		this.realPrice = realPrice;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getRealPv() {
		return this.realPv;
	}

	public void setRealPv(BigDecimal realPv) {
		this.realPv = realPv;
	}

	public BigDecimal getPvRate() {
		return this.pvRate;
	}

	public void setPvRate(BigDecimal pvRate) {
		this.pvRate = pvRate;
	}

}
