package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private Long id;
	private Long messageId;
	private String replyContent;
	private String createdBy;
	private Date createTime;

	public Reply() {
	}

	public Reply(Long messageId, String replyContent, String createdBy,
			Date createTime) {
		this.messageId = messageId;
		this.replyContent = replyContent;
		this.createdBy = createdBy;
		this.createTime = createTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
