package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

/**
 * Uploadtemp generated by hbm2java
 */
public class Uploadtemp implements java.io.Serializable {

	private UploadtempId id;

	public Uploadtemp() {
	}

	public Uploadtemp(UploadtempId id) {
		this.id = id;
	}

	public UploadtempId getId() {
		return this.id;
	}

	public void setId(UploadtempId id) {
		this.id = id;
	}

}
