package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

/**
 * UploadtempId generated by hbm2java
 */
public class UploadtempId implements java.io.Serializable {

	private String uploader;
	private String uploadType;
	private String uploadFilePath;

	public UploadtempId() {
	}

	public UploadtempId(String uploader, String uploadType,
			String uploadFilePath) {
		this.uploader = uploader;
		this.uploadType = uploadType;
		this.uploadFilePath = uploadFilePath;
	}

	public String getUploader() {
		return this.uploader;
	}

	public void setUploader(String uploader) {
		this.uploader = uploader;
	}

	public String getUploadType() {
		return this.uploadType;
	}

	public void setUploadType(String uploadType) {
		this.uploadType = uploadType;
	}

	public String getUploadFilePath() {
		return this.uploadFilePath;
	}

	public void setUploadFilePath(String uploadFilePath) {
		this.uploadFilePath = uploadFilePath;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UploadtempId))
			return false;
		UploadtempId castOther = (UploadtempId) other;

		return ((this.getUploader() == castOther.getUploader()) || (this
				.getUploader() != null && castOther.getUploader() != null && this
				.getUploader().equals(castOther.getUploader())))
				&& ((this.getUploadType() == castOther.getUploadType()) || (this
						.getUploadType() != null
						&& castOther.getUploadType() != null && this
						.getUploadType().equals(castOther.getUploadType())))
				&& ((this.getUploadFilePath() == castOther.getUploadFilePath()) || (this
						.getUploadFilePath() != null
						&& castOther.getUploadFilePath() != null && this
						.getUploadFilePath().equals(
								castOther.getUploadFilePath())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUploader() == null ? 0 : this.getUploader().hashCode());
		result = 37
				* result
				+ (getUploadType() == null ? 0 : this.getUploadType()
						.hashCode());
		result = 37
				* result
				+ (getUploadFilePath() == null ? 0 : this.getUploadFilePath()
						.hashCode());
		return result;
	}

}
