package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserAccount201404 generated by hbm2java
 */
public class UserAccount201404 implements java.io.Serializable {

	private int accountId;
	private int userId;
	private Date accountDate;
	private Integer stat;
	private Double baseIn;
	private Double baseOut;
	private Double baseBalance;
	private Double repeatIn;
	private Double repeatOut;
	private Double repeatBalance;
	private Integer freePv;
	private Integer alreadyPv;
	private Integer buyPv;

	public UserAccount201404() {
	}

	public UserAccount201404(int accountId, int userId) {
		this.accountId = accountId;
		this.userId = userId;
	}

	public UserAccount201404(int accountId, int userId, Date accountDate,
			Integer stat, Double baseIn, Double baseOut, Double baseBalance,
			Double repeatIn, Double repeatOut, Double repeatBalance,
			Integer freePv, Integer alreadyPv, Integer buyPv) {
		this.accountId = accountId;
		this.userId = userId;
		this.accountDate = accountDate;
		this.stat = stat;
		this.baseIn = baseIn;
		this.baseOut = baseOut;
		this.baseBalance = baseBalance;
		this.repeatIn = repeatIn;
		this.repeatOut = repeatOut;
		this.repeatBalance = repeatBalance;
		this.freePv = freePv;
		this.alreadyPv = alreadyPv;
		this.buyPv = buyPv;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getAccountDate() {
		return this.accountDate;
	}

	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

	public Double getBaseIn() {
		return this.baseIn;
	}

	public void setBaseIn(Double baseIn) {
		this.baseIn = baseIn;
	}

	public Double getBaseOut() {
		return this.baseOut;
	}

	public void setBaseOut(Double baseOut) {
		this.baseOut = baseOut;
	}

	public Double getBaseBalance() {
		return this.baseBalance;
	}

	public void setBaseBalance(Double baseBalance) {
		this.baseBalance = baseBalance;
	}

	public Double getRepeatIn() {
		return this.repeatIn;
	}

	public void setRepeatIn(Double repeatIn) {
		this.repeatIn = repeatIn;
	}

	public Double getRepeatOut() {
		return this.repeatOut;
	}

	public void setRepeatOut(Double repeatOut) {
		this.repeatOut = repeatOut;
	}

	public Double getRepeatBalance() {
		return this.repeatBalance;
	}

	public void setRepeatBalance(Double repeatBalance) {
		this.repeatBalance = repeatBalance;
	}

	public Integer getFreePv() {
		return this.freePv;
	}

	public void setFreePv(Integer freePv) {
		this.freePv = freePv;
	}

	public Integer getAlreadyPv() {
		return this.alreadyPv;
	}

	public void setAlreadyPv(Integer alreadyPv) {
		this.alreadyPv = alreadyPv;
	}

	public Integer getBuyPv() {
		return this.buyPv;
	}

	public void setBuyPv(Integer buyPv) {
		this.buyPv = buyPv;
	}

}
