package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserAccountLog201404 generated by hbm2java
 */
public class UserAccountLog201404 implements java.io.Serializable {

	private long accountLogId;
	private Long userId;
	private Date actionTime;
	private String actionDesc;
	private Integer actionType;
	private BigDecimal baseIn;
	private BigDecimal baseOut;
	private BigDecimal baseBalance;
	private BigDecimal repeatIn;
	private BigDecimal repeatOut;
	private BigDecimal repeatBalance;

	public UserAccountLog201404() {
	}

	public UserAccountLog201404(long accountLogId) {
		this.accountLogId = accountLogId;
	}

	public UserAccountLog201404(long accountLogId, Long userId,
			Date actionTime, String actionDesc, Integer actionType,
			BigDecimal baseIn, BigDecimal baseOut, BigDecimal baseBalance,
			BigDecimal repeatIn, BigDecimal repeatOut, BigDecimal repeatBalance) {
		this.accountLogId = accountLogId;
		this.userId = userId;
		this.actionTime = actionTime;
		this.actionDesc = actionDesc;
		this.actionType = actionType;
		this.baseIn = baseIn;
		this.baseOut = baseOut;
		this.baseBalance = baseBalance;
		this.repeatIn = repeatIn;
		this.repeatOut = repeatOut;
		this.repeatBalance = repeatBalance;
	}

	public long getAccountLogId() {
		return this.accountLogId;
	}

	public void setAccountLogId(long accountLogId) {
		this.accountLogId = accountLogId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	public String getActionDesc() {
		return this.actionDesc;
	}

	public void setActionDesc(String actionDesc) {
		this.actionDesc = actionDesc;
	}

	public Integer getActionType() {
		return this.actionType;
	}

	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

	public BigDecimal getBaseIn() {
		return this.baseIn;
	}

	public void setBaseIn(BigDecimal baseIn) {
		this.baseIn = baseIn;
	}

	public BigDecimal getBaseOut() {
		return this.baseOut;
	}

	public void setBaseOut(BigDecimal baseOut) {
		this.baseOut = baseOut;
	}

	public BigDecimal getBaseBalance() {
		return this.baseBalance;
	}

	public void setBaseBalance(BigDecimal baseBalance) {
		this.baseBalance = baseBalance;
	}

	public BigDecimal getRepeatIn() {
		return this.repeatIn;
	}

	public void setRepeatIn(BigDecimal repeatIn) {
		this.repeatIn = repeatIn;
	}

	public BigDecimal getRepeatOut() {
		return this.repeatOut;
	}

	public void setRepeatOut(BigDecimal repeatOut) {
		this.repeatOut = repeatOut;
	}

	public BigDecimal getRepeatBalance() {
		return this.repeatBalance;
	}

	public void setRepeatBalance(BigDecimal repeatBalance) {
		this.repeatBalance = repeatBalance;
	}

}
