package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserRecharge generated by hbm2java
 */
public class UserRecharge implements java.io.Serializable {

	private String rechargeId;
	private Date rechargeTime;
	private String rechargeNum;
	private String userId;
	private String currency;
	private BigDecimal rechargeMoney;
	private String note;
	private BigDecimal creditedMoney;
	private Date creditedTime;
	private String auditUser;
	private BigDecimal pvRate;
	private BigDecimal pv;
	private String bankName;
	private String bankAccount;
	private String platform;
	private String param;

	public UserRecharge() {
	}

	public UserRecharge(String rechargeId) {
		this.rechargeId = rechargeId;
	}

	public UserRecharge(String rechargeId, Date rechargeTime,
			String rechargeNum, String userId, String currency,
			BigDecimal rechargeMoney, String note, BigDecimal creditedMoney,
			Date creditedTime, String auditUser, BigDecimal pvRate,
			BigDecimal pv, String bankName, String bankAccount,
			String platform, String param) {
		this.rechargeId = rechargeId;
		this.rechargeTime = rechargeTime;
		this.rechargeNum = rechargeNum;
		this.userId = userId;
		this.currency = currency;
		this.rechargeMoney = rechargeMoney;
		this.note = note;
		this.creditedMoney = creditedMoney;
		this.creditedTime = creditedTime;
		this.auditUser = auditUser;
		this.pvRate = pvRate;
		this.pv = pv;
		this.bankName = bankName;
		this.bankAccount = bankAccount;
		this.platform = platform;
		this.param = param;
	}

	public String getRechargeId() {
		return this.rechargeId;
	}

	public void setRechargeId(String rechargeId) {
		this.rechargeId = rechargeId;
	}

	public Date getRechargeTime() {
		return this.rechargeTime;
	}

	public void setRechargeTime(Date rechargeTime) {
		this.rechargeTime = rechargeTime;
	}

	public String getRechargeNum() {
		return this.rechargeNum;
	}

	public void setRechargeNum(String rechargeNum) {
		this.rechargeNum = rechargeNum;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getRechargeMoney() {
		return this.rechargeMoney;
	}

	public void setRechargeMoney(BigDecimal rechargeMoney) {
		this.rechargeMoney = rechargeMoney;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public BigDecimal getCreditedMoney() {
		return this.creditedMoney;
	}

	public void setCreditedMoney(BigDecimal creditedMoney) {
		this.creditedMoney = creditedMoney;
	}

	public Date getCreditedTime() {
		return this.creditedTime;
	}

	public void setCreditedTime(Date creditedTime) {
		this.creditedTime = creditedTime;
	}

	public String getAuditUser() {
		return this.auditUser;
	}

	public void setAuditUser(String auditUser) {
		this.auditUser = auditUser;
	}

	public BigDecimal getPvRate() {
		return this.pvRate;
	}

	public void setPvRate(BigDecimal pvRate) {
		this.pvRate = pvRate;
	}

	public BigDecimal getPv() {
		return this.pv;
	}

	public void setPv(BigDecimal pv) {
		this.pv = pv;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

}
