package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserCash generated by hbm2java
 */
public class UserCash implements java.io.Serializable {

	private String cashId;
	private Date cashTime;
	private String cashNum;
	private String userId;
	private BigDecimal cashPv;
	private String currency;
	private BigDecimal pvRate;
	private BigDecimal cashMoney;
	private String note;
	private BigDecimal fee;
	private BigDecimal tax;
	private BigDecimal otherFee;
	private String bankName;
	private String bankBrance;
	private String bankAccount;
	private String accountName;
	private Integer stat;
	private BigDecimal creditedMoney;
	private Date creditedTime;
	private String operator;

	public UserCash() {
	}

	public UserCash(String cashId) {
		this.cashId = cashId;
	}

	public UserCash(String cashId, Date cashTime, String cashNum,
			String userId, BigDecimal cashPv, String currency,
			BigDecimal pvRate, BigDecimal cashMoney, String note,
			BigDecimal fee, BigDecimal tax, BigDecimal otherFee,
			String bankName, String bankBrance, String bankAccount,
			String accountName, Integer stat, BigDecimal creditedMoney,
			Date creditedTime, String operator) {
		this.cashId = cashId;
		this.cashTime = cashTime;
		this.cashNum = cashNum;
		this.userId = userId;
		this.cashPv = cashPv;
		this.currency = currency;
		this.pvRate = pvRate;
		this.cashMoney = cashMoney;
		this.note = note;
		this.fee = fee;
		this.tax = tax;
		this.otherFee = otherFee;
		this.bankName = bankName;
		this.bankBrance = bankBrance;
		this.bankAccount = bankAccount;
		this.accountName = accountName;
		this.stat = stat;
		this.creditedMoney = creditedMoney;
		this.creditedTime = creditedTime;
		this.operator = operator;
	}

	public String getCashId() {
		return this.cashId;
	}

	public void setCashId(String cashId) {
		this.cashId = cashId;
	}

	public Date getCashTime() {
		return this.cashTime;
	}

	public void setCashTime(Date cashTime) {
		this.cashTime = cashTime;
	}

	public String getCashNum() {
		return this.cashNum;
	}

	public void setCashNum(String cashNum) {
		this.cashNum = cashNum;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public BigDecimal getCashPv() {
		return this.cashPv;
	}

	public void setCashPv(BigDecimal cashPv) {
		this.cashPv = cashPv;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public BigDecimal getPvRate() {
		return this.pvRate;
	}

	public void setPvRate(BigDecimal pvRate) {
		this.pvRate = pvRate;
	}

	public BigDecimal getCashMoney() {
		return this.cashMoney;
	}

	public void setCashMoney(BigDecimal cashMoney) {
		this.cashMoney = cashMoney;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	public BigDecimal getOtherFee() {
		return this.otherFee;
	}

	public void setOtherFee(BigDecimal otherFee) {
		this.otherFee = otherFee;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankBrance() {
		return this.bankBrance;
	}

	public void setBankBrance(String bankBrance) {
		this.bankBrance = bankBrance;
	}

	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

	public BigDecimal getCreditedMoney() {
		return this.creditedMoney;
	}

	public void setCreditedMoney(BigDecimal creditedMoney) {
		this.creditedMoney = creditedMoney;
	}

	public Date getCreditedTime() {
		return this.creditedTime;
	}

	public void setCreditedTime(Date creditedTime) {
		this.creditedTime = creditedTime;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
