package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserPlace generated by hbm2java
 */
public class UserPlace implements java.io.Serializable {

	private String placeId;
	private Date placeTime;
	private String bonusUserId;
	private String userId;
	private BigDecimal buyPv;
	private BigDecimal bonusRate;
	private BigDecimal bonusPv;

	public UserPlace() {
	}

	public UserPlace(String placeId) {
		this.placeId = placeId;
	}

	public UserPlace(String placeId, Date placeTime, String bonusUserId,
			String userId, BigDecimal buyPv, BigDecimal bonusRate,
			BigDecimal bonusPv) {
		this.placeId = placeId;
		this.placeTime = placeTime;
		this.bonusUserId = bonusUserId;
		this.userId = userId;
		this.buyPv = buyPv;
		this.bonusRate = bonusRate;
		this.bonusPv = bonusPv;
	}

	public String getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(String placeId) {
		this.placeId = placeId;
	}

	public Date getPlaceTime() {
		return this.placeTime;
	}

	public void setPlaceTime(Date placeTime) {
		this.placeTime = placeTime;
	}

	public String getBonusUserId() {
		return this.bonusUserId;
	}

	public void setBonusUserId(String bonusUserId) {
		this.bonusUserId = bonusUserId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public BigDecimal getBuyPv() {
		return this.buyPv;
	}

	public void setBuyPv(BigDecimal buyPv) {
		this.buyPv = buyPv;
	}

	public BigDecimal getBonusRate() {
		return this.bonusRate;
	}

	public void setBonusRate(BigDecimal bonusRate) {
		this.bonusRate = bonusRate;
	}

	public BigDecimal getBonusPv() {
		return this.bonusPv;
	}

	public void setBonusPv(BigDecimal bonusPv) {
		this.bonusPv = bonusPv;
	}

}
