package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserAccount201312 generated by hbm2java
 */
public class UserAccount201312 implements java.io.Serializable {

	private String accountId;
	private String userId;
	private Date accountDate;
	private Integer stat;
	private BigDecimal baseIn;
	private BigDecimal baseOut;
	private BigDecimal baseBalance;
	private BigDecimal repeatIn;
	private BigDecimal repeatOut;
	private BigDecimal repeatBalance;
	private BigDecimal freePv;
	private BigDecimal alreadyPv;
	private BigDecimal buyPv;

	public UserAccount201312() {
	}

	public UserAccount201312(String accountId) {
		this.accountId = accountId;
	}

	public UserAccount201312(String accountId, String userId, Date accountDate,
			Integer stat, BigDecimal baseIn, BigDecimal baseOut,
			BigDecimal baseBalance, BigDecimal repeatIn, BigDecimal repeatOut,
			BigDecimal repeatBalance, BigDecimal freePv, BigDecimal alreadyPv,
			BigDecimal buyPv) {
		this.accountId = accountId;
		this.userId = userId;
		this.accountDate = accountDate;
		this.stat = stat;
		this.baseIn = baseIn;
		this.baseOut = baseOut;
		this.baseBalance = baseBalance;
		this.repeatIn = repeatIn;
		this.repeatOut = repeatOut;
		this.repeatBalance = repeatBalance;
		this.freePv = freePv;
		this.alreadyPv = alreadyPv;
		this.buyPv = buyPv;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Date getAccountDate() {
		return this.accountDate;
	}

	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	public Integer getStat() {
		return this.stat;
	}

	public void setStat(Integer stat) {
		this.stat = stat;
	}

	public BigDecimal getBaseIn() {
		return this.baseIn;
	}

	public void setBaseIn(BigDecimal baseIn) {
		this.baseIn = baseIn;
	}

	public BigDecimal getBaseOut() {
		return this.baseOut;
	}

	public void setBaseOut(BigDecimal baseOut) {
		this.baseOut = baseOut;
	}

	public BigDecimal getBaseBalance() {
		return this.baseBalance;
	}

	public void setBaseBalance(BigDecimal baseBalance) {
		this.baseBalance = baseBalance;
	}

	public BigDecimal getRepeatIn() {
		return this.repeatIn;
	}

	public void setRepeatIn(BigDecimal repeatIn) {
		this.repeatIn = repeatIn;
	}

	public BigDecimal getRepeatOut() {
		return this.repeatOut;
	}

	public void setRepeatOut(BigDecimal repeatOut) {
		this.repeatOut = repeatOut;
	}

	public BigDecimal getRepeatBalance() {
		return this.repeatBalance;
	}

	public void setRepeatBalance(BigDecimal repeatBalance) {
		this.repeatBalance = repeatBalance;
	}

	public BigDecimal getFreePv() {
		return this.freePv;
	}

	public void setFreePv(BigDecimal freePv) {
		this.freePv = freePv;
	}

	public BigDecimal getAlreadyPv() {
		return this.alreadyPv;
	}

	public void setAlreadyPv(BigDecimal alreadyPv) {
		this.alreadyPv = alreadyPv;
	}

	public BigDecimal getBuyPv() {
		return this.buyPv;
	}

	public void setBuyPv(BigDecimal buyPv) {
		this.buyPv = buyPv;
	}

}
