package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserPointGoods generated by hbm2java
 */
public class UserPointGoods implements java.io.Serializable {

	private String pointGoodsId;
	private Date pickTime;
	private String userId;
	private BigDecimal buyPv;
	private String orderId;

	public UserPointGoods() {
	}

	public UserPointGoods(String pointGoodsId) {
		this.pointGoodsId = pointGoodsId;
	}

	public UserPointGoods(String pointGoodsId, Date pickTime, String userId,
			BigDecimal buyPv, String orderId) {
		this.pointGoodsId = pointGoodsId;
		this.pickTime = pickTime;
		this.userId = userId;
		this.buyPv = buyPv;
		this.orderId = orderId;
	}

	public String getPointGoodsId() {
		return this.pointGoodsId;
	}

	public void setPointGoodsId(String pointGoodsId) {
		this.pointGoodsId = pointGoodsId;
	}

	public Date getPickTime() {
		return this.pickTime;
	}

	public void setPickTime(Date pickTime) {
		this.pickTime = pickTime;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public BigDecimal getBuyPv() {
		return this.buyPv;
	}

	public void setBuyPv(BigDecimal buyPv) {
		this.buyPv = buyPv;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

}
