package cn.jbit.bean;

// Generated 2017-3-1 15:51:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UserBuyBonus generated by hbm2java
 */
public class UserBuyBonus implements java.io.Serializable {

	private String buyBonusId;
	private String bonusMonth;
	private Date calTime;
	private String bonusUserId;
	private BigDecimal buyPv;
	private BigDecimal bonusRate;
	private BigDecimal bonusPv;

	public UserBuyBonus() {
	}

	public UserBuyBonus(String buyBonusId) {
		this.buyBonusId = buyBonusId;
	}

	public UserBuyBonus(String buyBonusId, String bonusMonth, Date calTime,
			String bonusUserId, BigDecimal buyPv, BigDecimal bonusRate,
			BigDecimal bonusPv) {
		this.buyBonusId = buyBonusId;
		this.bonusMonth = bonusMonth;
		this.calTime = calTime;
		this.bonusUserId = bonusUserId;
		this.buyPv = buyPv;
		this.bonusRate = bonusRate;
		this.bonusPv = bonusPv;
	}

	public String getBuyBonusId() {
		return this.buyBonusId;
	}

	public void setBuyBonusId(String buyBonusId) {
		this.buyBonusId = buyBonusId;
	}

	public String getBonusMonth() {
		return this.bonusMonth;
	}

	public void setBonusMonth(String bonusMonth) {
		this.bonusMonth = bonusMonth;
	}

	public Date getCalTime() {
		return this.calTime;
	}

	public void setCalTime(Date calTime) {
		this.calTime = calTime;
	}

	public String getBonusUserId() {
		return this.bonusUserId;
	}

	public void setBonusUserId(String bonusUserId) {
		this.bonusUserId = bonusUserId;
	}

	public BigDecimal getBuyPv() {
		return this.buyPv;
	}

	public void setBuyPv(BigDecimal buyPv) {
		this.buyPv = buyPv;
	}

	public BigDecimal getBonusRate() {
		return this.bonusRate;
	}

	public void setBonusRate(BigDecimal bonusRate) {
		this.bonusRate = bonusRate;
	}

	public BigDecimal getBonusPv() {
		return this.bonusPv;
	}

	public void setBonusPv(BigDecimal bonusPv) {
		this.bonusPv = bonusPv;
	}

}
